### ISSUE TITLE
Research: what do users need in terms of dashboard/infor reported?

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#137]
- [x] My Dashboard (see #2)
- [x] Home page (global dashboard) - at a glance or widget reporting (#213)
- [x] Reports list (see #208, #209, #210, #211, #212)
- [x] #60
- [x] #70
- [x] #81 
- [x] #82

**Comment by NicoledeGreef** [comment]
Mockup of Global Dashboard concept:

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/907cec3c-9557-42f0-9389-300fcb4f750f)

New ticket(s) being created to aid in development of the widgets.

**Comment by NicoledeGreef** [comment]
Will close once the new tickets are created.
