### ISSUE TITLE
Document the nature of dataset type/format/product type

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#171]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5180578276

---
Currently there are three taxonomies and three associated entity reference fields That server a similar purpose.

the vocabularies and associated entity reference fields are:

- `product_type`
- `data_set_type`
- `data_set_format`

These can all be managed by a single three level vocabulary, for example
**Product type (level 1)** | **Data set type (level 2)** | **Data set format (level 3)**
-- | -- | --
Data | Database | MSSQL
Report | File | MS Word

## Task

- [x] remove vocabulary ` product_type`
- [x] remove vocabulary `data_set_format`
- [x]  remove field `field_product_type` from content type `data_set`
- [x] remove field `field_data_set_format` from content type `data_set`
- [x] set form display for `field_data_set_type` to use SHS
- [x] on the node view, show all levels of the taxonomy
- [x] add to the [online documentation](https://mfin-data-catalogue.apps.silver.devops.gov.bc.ca/documentation) information on how the `data_set_type` should use three levels of taxonomy to show _Product type_, _Data set type_ and _data set format_

**Comment by CraigClark** [comment]
@NicoledeGreef , I've tested this on dv21 and it works fine. For now, you do not need to select the deepest level of the taxonomy. Let me know if this is something you need it do do.



![dataset type display rendered on node view shows report > document > MS Word](https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/4fb1cce8-4a33-4907-848d-599461144dd8)

**Comment by CraigClark** [comment]
TODO: Add documentation

**Comment by CraigClark** [comment]
documentation: https://mfin-data-catalogue.apps.silver.devops.gov.bc.ca/documentation/dataset-type
