### ISSUE TITLE
Split build page into 5 sections

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#198]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5360621512

---

## Task

Using the Figma prototype as a guide, develop the build page for data catalogue editors.

Some aspects of the prototype relate to having support for saving a draft (forward revision). These will be implemented in #224.

The difference between new and existing will be handled in #226.

## Resources

- [Mobile build page prototype for a new MR](https://www.figma.com/proto/QFQoyhpG1qvtBwVuuBVikk/design-prototypes?type=design&node-id=335-4035&t=wCcGML7x1ikw40nH-1&scaling=scale-down&page-id=291%3A12856&starting-point-node-id=373%3A19167)
- [Desktop build page prototype for a new MR](https://www.figma.com/proto/QFQoyhpG1qvtBwVuuBVikk/design-prototypes?type=design&node-id=383-22147&t=N3BsbEmGDfSmV2Gu-1&scaling=scale-down&page-id=381%3A19173&starting-point-node-id=381%3A19302&mode=design)
- [Mobile build page for an existing MR](https://www.figma.com/proto/QFQoyhpG1qvtBwVuuBVikk/design-prototypes?type=design&node-id=342-16944&t=rhwCYzqdIqTztHQS-1&scaling=scale-down&page-id=291%3A12856&starting-point-node-id=373%3A19167&mode=design)
- [Desktop build page for an existing MR](https://www.figma.com/proto/QFQoyhpG1qvtBwVuuBVikk/design-prototypes?type=design&node-id=383-26136&t=BtJ2brnvzXi7CjpS-1&scaling=scale-down&page-id=381%3A19173&starting-point-node-id=381%3A19302&mode=design)
- [Bootstrap 5 documentation](https://getbootstrap.com/docs/5.3/getting-started/introduction/)
- [BC Base-build icon system](https://github.com/bcgov/bcbb/wiki/Using-icons)

> **Note**: to see how display modes, page manager and twig templates work together, see RSAMS [git repo](https://github.com/openplus/site-rsams) and [dv site](https://hcdev.openplus.ca/).

### Working with the prototypes

The Figma prototypes are a generalization of the theme, they are not an exact implementation of functionality. For example, on the build page, where it says 'required', it's an indication of what a required field would look like, it does not mean a specific field is required as per the prototype. So the task would be to make sure any require field is red with the asterisk, it is not to set the field as required.

### Working with Bootstrap 5

We should be able to implement all of this with existing Bootstrap 5 classes. Please talk to Craig before adding any custom CSS. We want to stick to the existing framework as much as possible.

### Before work begins

Review existing configuration, twig templates and any other custom theme or modules that affect the build page and associated display modes. This is important to ensure we extend existing work instead of duplicating or overriding it.

### The build page

Use page manager for the build page. This has already been started here `/admin/structure/page_manager/manage/data_set_build/general`.

We will need new sections as defined in the prototype.

### Build page sections

These should be built with Display modes. Twig templates will be needed for the view mode and form mode for each section.

In each section, get rid of any of the drupal Cruft. We don't need it.

## Screenshots

Figma won't show you the columns to use for BS layout. Here's what they should be

![12 col BSD layout](https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/93c76fe8-0c29-472e-96b4-f26d5a576622)

## Definition of done

1. [x] Build page looks like the figma desktop prototype
2. [x] Build page looks like the figma mobile prototype
3. [x] Only users with access can see the build page, navigation items to get to the build page or access the display modes for the sections

**Comment by CraigClark** [comment]
This is partially done in https://github.com/bcgov/MFIN-Data-Catalogue/tree/feat-build-layout

The a page has been created in page builder, view and form modes have been set up and some twig. 

to do

- [x] In a build section, if there is no value in a field, it should show as "required" or "optional", as configured in the field settings.
- [x] the data dictionary (columns) should be a column count as per the prototype
- [x] text areas should truncate at 150 characters (or 15 words) and add an ellipse …
- [x] verify that the fields in the build page summary match the prototype, same order
- [x] verify that when a section is edited, fields match build page summary and are in the same order

this page us currently throwing errors, fixing the tabs might address this

<details>
<summary>error log for build page</summary>

[see error log](https://dv21.openplus.ca/admin/reports/dblog/event/24467)

Location | https://dv21.openplus.ca/node/76/build

Referrer | https://dv21.openplus.ca/data-set/test-access-none

```
Warning: Trying to access array offset on value of type null in dc_theme_preprocess_field__node__field_review_interval() (line 115 of /var/www/html/dv21.openplus.ca/html/themes/custom/dc_theme/dc_theme.theme)

#0 /var/www/html/dv21.openplus.ca/html/core/includes/bootstrap.inc(164): _drupal_error_handler_real(2, 'Trying to acces...', '/var/www/html/d...', 115)
#1 /var/www/html/dv21.openplus.ca/html/themes/custom/dc_theme/dc_theme.theme(115): _drupal_error_handler(2, 'Trying to acces...', '/var/www/html/d...', 115)
#2 [internal function]: dc_theme_preprocess_field__node__field_review_interval(Array, 'field', Array)
#3 /var/www/html/dv21.openplus.ca/html/core/lib/Drupal/Core/Theme/ThemeManager.php(285): call_user_func_array('dc_theme_prepro...', Array)
#4 /var/www/html/dv21.openplus.ca/html/core/lib/Drupal/Core/Render/Renderer.php(445): Drupal\Core\Theme\ThemeManager->render('field', Array)
#5 /var/www/html/dv21.openplus.ca/html/core/lib/Drupal/Core/Render/Renderer.php(204): Drupal\Core\Render\Renderer->doRender(Array, false)
#6 /var/www/html/dv21.openplus.ca/html/core/lib/Drupal/Core/Template/TwigExtension.php(474): Drupal\Core\Render\Renderer->render(Array)
#7 /var/www/html/dv21.openplus.ca/html/sites/default/files/php/twig/6539586c5910d_node--data-set--section-4_aw9UsDmW0MB0zFGzGnPbbM0cZ/__yaXqoldDJ3vVETmt2bIScRs0CqmuHysLP9cxhbDcY.php(182): Drupal\Core\Template\TwigExtension->escapeFilter(Object(Drupal\Core\Template\TwigEnvironment), Array, 'html', NULL, true)
#8 /var/www/html/dv21.openplus.ca/vendor/twig/twig/src/Template.php(394): __TwigTemplate_85792efe0e1cc18ba525f493a766d592->doDisplay(Array, Array)
#9 /var/www/html/dv21.openplus.ca/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#10 /var/www/html/dv21.openplus.ca/vendor/twig/twig/src/Template.php(379): Twig\Template->display(Array)
#11 /var/www/html/dv21.openplus.ca/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\Template->render(Array, Array)
#12 /var/www/html/dv21.openplus.ca/html/core/themes/engines/twig/twig.engine(53): Twig\TemplateWrapper->render(Array)
#13 /var/www/html/dv21.openplus.ca/html/core/lib/Drupal/Core/Theme/ThemeManager.php(372): twig_render_template('themes/custom/d...', Array)
#14 /var/www/html/dv21.openplus.ca/html/core/lib/Drupal/Core/Render/Renderer.php(445): Drupal\Core\Theme\ThemeManager->render('node', Array)
#15 /var/www/html/dv21.openplus.ca/html/core/lib/Drupal/Core/Render/Renderer.php(204): Drupal\Core\Render\Renderer->doRender(Array, false)
#16 /var/www/html/dv21.openplus.ca/html/core/lib/Drupal/Core/Template/TwigExtension.php(474): Drupal\Core\Render\Renderer->render(Array)
#17 /var/www/html/dv21.openplus.ca/html/sites/default/files/php/twig/6539586c5910d_block--entity-view--node._W3k_7dKUX3k38EFtA8U7z95Fc/J0DHV_pkTd1kGWe_tO19mKevsfwo5VMVqvjYke4vi-c.php(82): Drupal\Core\Template\TwigExtension->escapeFilter(Object(Drupal\Core\Template\TwigEnvironment), Array, 'html', NULL, true)
#18 /var/www/html/dv21.openplus.ca/vendor/twig/twig/src/Template.php(171): __TwigTemplate_6e27187094098442cd696bd6e6d7e158->block_content(Array, Array)
#19 /var/www/html/dv21.openplus.ca/html/sites/default/files/php/twig/6539586c5910d_block--entity-view--node._W3k_7dKUX3k38EFtA8U7z95Fc/J0DHV_pkTd1kGWe_tO19mKevsfwo5VMVqvjYke4vi-c.php(68): Twig\Template->displayBlock('content', Array, Array)
#20 /var/www/html/dv21.openplus.ca/vendor/twig/twig/src/Template.php(394): __TwigTemplate_6e27187094098442cd696bd6e6d7e158->doDisplay(Array, Array)
#21 /var/www/html/dv21.openplus.ca/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#22 /var/www/html/dv21.openplus.ca/vendor/twig/twig/src/Template.php(379): Twig\Template->display(Array)
#23 /var/www/html/dv21.openplus.ca/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\Template->render(Array, Array)
#24 /var/www/html/dv21.openplus.ca/html/core/themes/engines/twig/twig.engine(53): Twig\TemplateWrapper->render(Array)
#25 /var/www/html/dv21.openplus.ca/html/core/lib/Drupal/Core/Theme/ThemeManager.php(372): twig_render_template('themes/custom/d...', Array)
#26 /var/www/html/dv21.openplus.ca/html/core/lib/Drupal/Core/Render/Renderer.php(445): Drupal\Core\Theme\ThemeManager->render('block', Array)
#27 /var/www/html/dv21.openplus.ca/html/core/lib/Drupal/Core/Render/Renderer.php(458): Drupal\Core\Render\Renderer->doRender(Array)
#28 /var/www/html/dv21.openplus.ca/html/core/lib/Drupal/Core/Render/Renderer.php(204): Drupal\Core\Render\Renderer->doRender(Array, false)
#29 /var/www/html/dv21.openplus.ca/html/core/lib/Drupal/Core/Template/TwigExtension.php(474): Drupal\Core\Render\Renderer->render(Array)
#30 /var/www/html/dv21.openplus.ca/html/sites/default/files/php/twig/6539586c5910d_bcbb_main_sidebar_right.h_gSXut92ytlkyxS8ICx9LTB2Ap/bPN1O7bIEI0J18VHQrLp88L6eDODwa0P72oCJz9p1N4.php(78): Drupal\Core\Template\TwigExtension->escapeFilter(Object(Drupal\Core\Template\TwigEnvironment), Array, 'html', NULL, true)
#31 /var/www/html/dv21.openplus.ca/vendor/twig/twig/src/Template.php(394): __TwigTemplate_d07f3b0b98421881f057c10ecfbdb72d->doDisplay(Array, Array)
#32 /var/www/html/dv21.openplus.ca/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#33 /var/www/html/dv21.openplus.ca/vendor/twig/twig/src/Template.php(379): Twig\Template->display(Array)
#34 /var/www/html/dv21.openplus.ca/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\Template->render(Array, Array)
#35 /var/www/html/dv21.openplus.ca/html/core/themes/engines/twig/twig.engine(53): Twig\TemplateWrapper->render(Array)
#36 /var/www/html/dv21.openplus.ca/html/core/lib/Drupal/Core/Theme/ThemeManager.php(372): twig_render_template('modules/contrib...', Array)
#37 /var/www/html/dv21.openplus.ca/html/core/lib/Drupal/Core/Render/Renderer.php(445): Drupal\Core\Theme\ThemeManager->render('bcbb_main_sideb...', Array)
#38 /var/www/html/dv21.openplus.ca/html/core/lib/Drupal/Core/Render/Renderer.php(204): Drupal\Core\Render\Renderer->doRender(Array, false)
#39 /var/www/html/dv21.openplus.ca/html/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(238): Drupal\Core\Render\Renderer->render(Array, false)
#40 /var/www/html/dv21.openplus.ca/html/core/lib/Drupal/Core/Render/Renderer.php(592): Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}()
#41 /var/www/html/dv21.openplus.ca/html/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(239): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure))
#42 /var/www/html/dv21.openplus.ca/html/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(128): Drupal\Core\Render\MainContent\HtmlRenderer->prepare(Array, Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\CurrentRouteMatch))
#43 /var/www/html/dv21.openplus.ca/html/core/lib/Drupal/Core/EventSubscriber/MainContentViewSubscriber.php(90): Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse(Array, Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\CurrentRouteMatch))
#44 [internal function]: Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray(Object(Symfony\Component\HttpKernel\Event\ViewEvent), 'kernel.view', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher))
#45 /var/www/html/dv21.openplus.ca/html/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(111): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\ViewEvent), 'kernel.view', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher))
#46 /var/www/html/dv21.openplus.ca/vendor/symfony/http-kernel/HttpKernel.php(186): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch(Object(Symfony\Component\HttpKernel\Event\ViewEvent), 'kernel.view')
#47 /var/www/html/dv21.openplus.ca/vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#48 /var/www/html/dv21.openplus.ca/html/core/lib/Drupal/Core/StackMiddleware/Session.php(58): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#49 /var/www/html/dv21.openplus.ca/html/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(48): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#50 /var/www/html/dv21.openplus.ca/html/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#51 /var/www/html/dv21.openplus.ca/html/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#52 /var/www/html/dv21.openplus.ca/html/modules/contrib/shield/src/ShieldMiddleware.php(270): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#53 /var/www/html/dv21.openplus.ca/html/modules/contrib/shield/src/ShieldMiddleware.php(226): Drupal\shield\ShieldMiddleware->bypass(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#54 /var/www/html/dv21.openplus.ca/html/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(48): Drupal\shield\ShieldMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#55 /var/www/html/dv21.openplus.ca/html/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(51): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#56 /var/www/html/dv21.openplus.ca/html/core/lib/Drupal/Core/StackMiddleware/StackedHttpKernel.php(51): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#57 /var/www/html/dv21.openplus.ca/html/core/lib/Drupal/Core/DrupalKernel.php(704): Drupal\Core\StackMiddleware\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#58 /var/www/html/dv21.openplus.ca/html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#59 {main}
```
</details>

**Comment by CraigClark** [comment]
@lkmorlan could you please finish this up? I reviewed a couple of weeks ago, see my comment from October 25.

I tried to take a look again this morning. I get a WSOD on the build page, I tried to `git rebase 1.0.x` but it dodn't help. Error says it is looking for _page_manager.page_view_site_search_site_search-panels_variant-0"_ and it doesn't exist.

**Comment by CraigClark** [comment]
done
