### ISSUE TITLE
metadata content model addition: a flag that indicates whether Personal Information is present in the catalogued item

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#217]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5444627523

---
Add a new field to the metadata content model to represent whether there is PersonalInformation in the subject item. Can be a boolean (Yes/No)

This came up at a recent Finance Data Store inception session as well as in discussion around the latest iteration of the Info Security Standard.

Should be mandatory when metadata is created. Instead of displaying Yes or No, create a visual badge that displays near the title, similar to High Value.

**Comment by CraigClark** [comment]
@lkmorlan I have most of this done. We can make it required towards the end of the project.
Could you please write tests for this and merge to 1.0.x?

Sorry for the crazy long branch name, I created it from the issue and didn't think to shorten it.

Branch is here https://github.com/bcgov/MFIN-Data-Catalogue/tree/217-flag-personal-data

## What is done

- [x] field created/configured
- [x] added to node template

## ToDo

- [x] review
- [x] write tests
- [x] merge to 1.0.x
- [x] add to build page, Section 3, data usage
