### ISSUE TITLE
Implement draft revisions

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#224]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5483953033

---

When a data catalogue editor creates a new MR, its initial state is draft.

## Part 1 Creating the first draft

This will be done in #226.

## Part 2 Building a new MR

When the MR is first created, it shows up on the dashboard. From the dashboard, the user selects the _build_ button. this takes them to the build page. see #198.

On the build page, there are different build sections, each with an edit tab. Selecting _Edit_ opens a build section (see #222). Selecting _Save_ creates a new draft revision.

## Publishing an MR

Publishing happens from the build page. Editors can leave a revision comment if desired, select the _This is a complete review_ if needed and click _Publish_.

## Editing an MR

To edit an existing MR, select the build tab from a node or the build button on the _My published metadata records_ page.

This creates a new draft, user make their changes and publish.

## Pruner

Because the data dictionary can potentially have hundreds of rows, and they are going to get saved with every revision, we should run a pruner. This will be done in #191.

## Theme build page

Add revision comment, check box for complete review and publish button to the build page as per the prototype

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/e9982792-d3e9-4eb4-8e0d-18b876e39988)

[See on Figma](https://www.figma.com/proto/QFQoyhpG1qvtBwVuuBVikk/design-prototypes?type=design&node-id=383-26136&t=YI8285U2HApFxeVq-1&scaling=scale-down&page-id=381%3A19173&starting-point-node-id=381%3A19302&mode=design)

Definition of done

- [x] If I click _Save_ while in a build section, a new revision is created and I can see it under the revisions tab
- [x] if I click _Publish_ on the Build page, a published revision is created. I see this under the view tab and I see it under the revisions tab
- [x] add revision messages to build page
- [x] add _check if this is a full review_ checkbox
- [x] add publish button to build page

**Comment by CraigClark** [comment]
I tested revisions logged in with an IDIR account with role MR editor. It doesn't work as expected, I'm assuming because #235 is not done.

When I create a MR, after publish the first one, I cannot make any changes. 

to duplicate

1. login as MR editor
2. create new MR
3. enter some values in the field in the first build section
4. save
5. on build page, publish
6. click build tab
7. edit a section
8. save
9. see that nothing happens

**Comment by CraigClark** [comment]
On this page https://dv21.openplus.ca/node/80/edit?display=section_1&destination=/node/80/build

I see 
<img width="1090" alt="image" src="https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/4e1e0727-35ab-4c4b-a455-fdee15826bfb">

I shouldn't see this here

**Comment by CraigClark** [comment]
This works, permissions to be done in a separate feature
