### ISSUE TITLE
Review: list of issues - pre-alpha release

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#261]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5640742274

---

# Pre-alpha release general review

> [!NOTE]
> Check items off as they are completed

Reviewed on 1.0.x  

## General observations

- [x] the pages look off balance with no footer. There's a feature request to add an org specific footer. We should implement that before launch, or at lease a footer with some generic BC links in it, or an empty blue/gold bar. #176 #265 
- [x] because we are using the white logo, when a page is printed, you can't read the text. Resolve this with the print style sheet. #57
- [x] ~~On dashboard and build pages add _aria_ tags to build and view buttons.~~ Will be fixed in #271.
- [x] Use the `dc_theme` for edit view.
- [x] @CraigClark the path for the home page is currenty dashboard. it should be _Home//_

## Search

- [x] Remove "Advanced search" link from home page and dashboard.

### Role: anonymous

- [x]  @CraigClark  Search shows `html` in snippet [fix submitted](https://github.com/bcgov/MFIN-Data-Catalogue/tree/fix-strip-html-from-search-result)
- [x] @CraigClark Pager color should be using BC primary, the same color as the background on the active page
- [x] *Reset* button should not be visible unless a value has been submitted in the search input field
- [x]  @CraigClark  on search block on home page, button does not align with input field. This is happening because the search button uses absolute positioning. The label Find metadata records changes the size of the container.  
  >[!NOTE] This will be addressed in issue [#19](https://github.com/bcgov/bcbb-theme/issues/19) of the base theme
- [x] @CraigClark  when printing this page, [1] remove right column, it's empty but not a good use of space. [2] Remove the search input field and buttons, [3] remove '*show filters*', [4] remove '*displaying results*', [5] remove the pager | see #57

### Role: DC user, Org: none

- [x] there is a *cancel* button in the *Save this search* block, when I click it, I am directed to the dashboard. There is no need for a cancel button on this form, remove it.

### Misc search related

- [x] on openshift environment, *test* and *demo* were not returning results despite plenty of content. Re-indexing worked, but this should be happening automatically. (check cron)
- [x] @lkmorlan  change path for search from `/data-set` to `search`
- [x] @CraigClark update path auto so MRs don't use `/data-set` in the URL
- [x] @CraigClark  stemming isn't working properly, consider [snowball stemmer](https://www.drupal.org/project/snowball_stemmer)
- [x] @CraigClark  compare search settings against an established site like CATSA or RSAMS
- [x] @CraigClark solr should be the search index
- [x] set facets to use hierarchy instead of showing all terms in the sidebar

## Admin

- [x] @CraigClark  remove ability for admins to assign the role used for authenticated user. There is a view for this `/admin/structure/views/view/organizations

### Role: DC user, Org: none

- [x] @CraigClark  add space between *Record visibility* and data set description (body)
- [x] @CraigClark  keep visual placement of bookmark link on desktop, in the DOM and on mobile, it should be between the title and the start of the content. see issue #251
- [x] @CraigClark *Data custodian* field label should be normal font weight, see class `field--name-field-data-custodian`.
- [x] @CraigClark  find a way to separate *Data set editor* and *permalink* from the data dictionary. There is not enough distinction that this is separate information from the data dictionary.
- [x] @CraigClark   *Personal information* field value should appear in the *Data usage* section of the sidebar. It should always show a `yes` or `no` value. This is independent behavior from the alert at the top of the Data set when Data set does contain personal info.
- [x] @CraigClark   add space between header an breadcrumb. it should be ½ the space that exists between the breadcrumb and the title
- [x]  @CraigClark  when printing this page, [1] remove search bar from header. [2] Remove local task links [3] remove links to download data dictionary [4] remove permlink [5] remove bookmark link [6] remove border around sidebar info and replace with a heavier top margin [7] remove documentation and dashboard links from header [8] remove environment variable | see #57

## Metadata record build

It isn't clear if I should be able to delete an MR or not. see #219

- [x]  @CraigClark  All edit sections: align *Save* and *Cancel* buttons to the left
- [x]  @CraigClark  All edit sections: change help text color to `var(--bs-gray-600)`
- [x]  @CraigClark  All edit sections: make help text smaller, we can add class `small` or target with `font-size: 0.875em;`
- [x] All edit sections: get rid of `About text formats` link
- [x] I can publish a record without filling out the required fields, publish should fail with a message if I try to do this
- [x] Nice to have: A list in the sidebar of any required fields that have not been filled out. See RSAMS for a example
- [x] Labels look inconsistent. In some cases a label for a field is `<h4 class="label">…</h4>` and in others it `<label for="…">…</label>`.We can make things look the same with `<label for="…" class="label">…</label>`. The `<h4>` is another issue, it appears that it is being used for display, not hierachy which isn't correct.
- [x] SHS fails if you are logged in as an editor, there is a patch to fix this <https://www.drupal.org/project/shs/issues/3357151> | Joel has applied the patch, it needs to be tested. Fixed in #215.
- [x]  @CraigClark  set a max width on help text so it is kept to around 60CPL (Characters Per Line)
- [x] remove class `button-small` from _Remove_ button at `/node/NID/edit?display=section_5`,[dv21 example here](https://dv21.openplus.ca/node/79/edit?display=section_5), this is the data dictionary paragraphs 
  ![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/2c07f165-ea0c-42fd-83e8-d5ef8ba01ce1)

### Section 1: Details

- ~~Add Data set name in this section so user's know this is where they can change the title~~ Nixing this idea for now. It will involve too much custom code for what it is designed to do.

#### Edit Section 1: Details

- [x]  @CraigClark  Series and datset fields are too wide on destop for select lists. Try `max-width: 50%` on `lg-min` and up.
- [x]  @CraigClark  Data set type should use SHS

### Section 2: Data description

- [x] add *Review interval* here so users know where to change it

#### Edit Section 2: Data description

- [x] @CraigClark   review interval input is too long, override `.form-control {width: 100%}` with `{width: auto}`

#### Edit Section 3: Data usage

- [x]  @CraigClark  Personal information radios should be in-line
- [x]  @CraigClark  Do something around *Used it datasets*, *maybe* a container? something to show that the fields and *Add another item* are all related to each other

#### Edit Section 4: Data value

- [x]  @CraigClark  Fix help text on information schedule, it is cut off. This should be a link to the documentation for this feature, `/node/53`

### Section 5: Data dictionary

- [x] logged in as editor, clicking on *Import/export data columns* returns *the requested page could not be found.*. As administrator, this works as expected. Fixed in #264.

##### Edit Section 5: Data dictionary: Import data columns

- [x] cancel button should have the same style as the cancel button in the build sections

##### Edit Section 5: Data dictionary: Add columns in UI (Paragraph)

- [x] Remove *About text fields* link on all textarea fields
- [x]  @CraigClark  Typo in help text for *Column name*, `he name of the column in the dataset.` should be `The name of the column in the dataset.`
- [x] @CraigClark   add spacing between fields to differentiate related items, it is hard to tell where one input ends and the next begins
- [x] @CraigClark   Select lists are too wide on desktop. Try `max-width: 50%` on `lg-min` and up.
- [x]  @CraigClark  ~~put all the provenance stuff in a container to show they are related~~ looks fine now that some theming has been applied.
- [x] @CraigClark   some fields have a short input value, for example a number, but the input width is 100%. Set these to be auto. That might look uneven, if it does, set a % value on breakpoints that looks civilized.

**Comment by CraigClark** [comment]
- [ ] on dashboard and build pages add _aria_ tags to build and view buttons

**Comment by CraigClark** [comment]
Checkbox for this is above; will be addressed in #19.

For the misaligned search icon on the home page and the dashboard, we need to change the HTML so there is a wrapper around the text input and the icon

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/769c31ae-b32f-43da-839d-c7bb43840384)

Can we please replace the html?

## Current HTML
```html
<div class="bcbb-search-api-form block block-bcbb-search block-bcbb-search-api-block" data-drupal-selector="bcbb-search-api-form">
  <form action="/" method="post" id="bcbb-search-api-form" accept-charset="UTF-8" role="search">
    <input data-drupal-selector="edit-search-url" type="hidden" name="search_url" value="/data-set">
    <div class="js-form-item form-item js-form-type-textfield form-type-textfield js-form-item-search-keyword form-item-search-keyword">
      <label for="edit-search-keyword">Find metadata records</label>
      <input data-drupal-selector="edit-search-keyword" aria-describedby="edit-search-keyword--description" type="text" id="edit-search-keyword" name="search_keyword" value="" maxlength="255" placeholder="" class="form-text form-control">
      <div id="edit-search-keyword--description" class="description">
        <a href="/data-set">Advanced search</a>
      </div>
    </div>
    <input aria-label="Do search" class="icon-bi button js-form-submit form-submit btn btn-primary" data-drupal-selector="edit-submit" type="submit" id="edit-submit" name="op" value="">
    <input autocomplete="off" data-drupal-selector="form-d4nbfh-mmbogrc7-wt2r0xcrgz2qb8al6w0pib7lh0" type="hidden" name="form_build_id" value="form-d4NbFH-_mmbOgrC7_Wt2r0XcRGZ2qb8AL6w0PiB7lH0">
    <input data-drupal-selector="edit-bcbb-search-api-form" type="hidden" name="form_id" value="bcbb_search_api_form">
  </form>
</div>
```
**With** 


## New HTML
```HTML
<div class="bcbb-search-api-form block block-bcbb-search block-bcbb-search-api-block" data-drupal-selector="bcbb-search-api-form">
  <form action="/" method="post" id="bcbb-search-api-form" accept-charset="UTF-8" role="search">
    <input data-drupal-selector="edit-search-url" type="hidden" name="search_url" value="/data-set">
    <div class="js-form-item form-item js-form-type-textfield form-type-textfield js-form-item-search-keyword form-item-search-keyword">
      <label for="edit-search-keyword">Find metadata records</label>
      <div class="d-flex position-relative">
        <input data-drupal-selector="edit-search-keyword" aria-describedby="edit-search-keyword--description" type="text" id="edit-search-keyword" name="search_keyword" value="" maxlength="255" placeholder="" class="form-text form-control">
        <input aria-label="Do search" class="icon-bi button js-form-submit form-submit btn btn-primary" data-drupal-selector="edit-submit" type="submit" id="edit-submit" name="op" value="">
        <input autocomplete="off" data-drupal-selector="form-d4nbfh-mmbogrc7-wt2r0xcrgz2qb8al6w0pib7lh0" type="hidden" name="form_build_id" value="form-d4NbFH-_mmbOgrC7_Wt2r0XcRGZ2qb8AL6w0PiB7lH0">
        <input data-drupal-selector="edit-bcbb-search-api-form" type="hidden" name="form_id" value="bcbb_search_api_form">
      </div>
      <div id="edit-search-keyword--description" class="description">
        <a href="/data-set">Advanced search</a>
      </div>
    </div>
  </form>
</div>
```

**Comment by CraigClark** [comment]
alignment of search icon on home and dashboard is fixed, still needs tests and merge see branch [261-remove-advanced-search-link](https://github.com/bcgov/MFIN-Data-Catalogue/tree/261-remove-advanced-search-link)

**Comment by CraigClark** [comment]
pager link color updated in bcbb_theme

**Comment by CraigClark** [comment]
Dashboard replaced with _Home_ for the front page and title removed as requested by @NicoledeGreef 

Changes are in this branch https://github.com/bcgov/MFIN-Data-Catalogue/tree/261-set-homepage

**Comment by CraigClark** [comment]
@lkmorlan I tried to change the search page path in page manager from _data-set,_  to _search_ but it didn't work. You will need to look after this one. It seems that there are a lot of references in code to _data-set_  in the path that will need to be removed. We no longer need it for breadcrumbs for example.

**Comment by CraigClark** [comment]
>[!NOTE]
> I installed snowball stemmer and received a notice that it's not recommended for SOLR. Stemmer seems to be working, we can create a stemming specific task if needed down the road

**Comment by CraigClark** [comment]
Search seems to be indexing. We can create an issue if it fails again

**Comment by CraigClark** [comment]
Bookmarks is now in the correct order in the DOM, waiting for review and merge see 
https://github.com/bcgov/MFIN-Data-Catalogue/tree/261-bookmarks-placement
