### ISSUE TITLE
SSO with IDIR for metadata providers and other users

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#31]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/4608683215

---

## User story

As a user of the Finance Data Catalogue, I want to login with my common Government account (IDIR) credentials so that the experience is consistent with other Government systems.

As a Product Owner for the Finance Data Catalogue, I want users to be able to log in the the product so that they can actively test what is being delivered so that the feedback loop is short and we can pivot if needed.

## This feature support the following requirements

[alpha release](https://openplus.monday.com/boards/3958997205/pulses/4605939234)

## Additional context

The o365 module has been installed.

The development site is at http://mfin-data-catalogue.apps.silver.devops.gov.bc.ca

## ToDo

- [ ] install modules
- [ ] get client id
- [ ] get client secret
- [ ] get tenant ID
- [ ] configure to work on azure cloud
- [ ] tests

## Estimated level of effort

- 2 days

## Definition of done (DoD)
- [ ] MFIN staff can log into site using their o365 credentials

### Automated functional tests

- [ ] I have written functional tests for this feature
- [ ] I have run the functional tests and they pass

### Automated site tests

- [ ] I have written site tests for this feature
- [ ] I have run the site tests and they pass

### This feature requires manual testing

1. first test step …
2. second test step …
3. etc …

**Comment by NicoledeGreef** [comment]
Need vault set up for this.

**Comment by CraigClark** [comment]
I have installed the modules we need for this using [Office 365 connector](https://www.drupal.org/project/o365).

We need the following info from BC:

1. client_id
2. client_secret
3. tenant_id

There is documentation on this at https://www.drupal.org/docs/contributed-modules/office-365-connector/setting-up-an-azure-app

@NicoledeGreef

**Comment by NicoledeGreef** [comment]
As per https://github.com/bcgov/sso-keycloak/wiki/SSO-Onboarding
This is a self-service item using the Common Hosted Single Sign-on App:
https://bcgov.github.io/sso-requests

Someone drafted a request and saved it for MFIN Data Catalogue already.  I added some missing info just now.  Might be best if a developer looked it over and continued the request to obtain the secret(s). @sylus @chrislaick @lkmorlan @CraigClark

**Comment by NicoledeGreef** [comment]
Implementation of SSO is done; there is a bcbb ticket for some minor adjustments (button labeling and options).
