### ISSUE TITLE
check / clean-up unused fields

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#389]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6290851387

---

In the early part of the project, the field token module was used to combine fields so that they could be used by the information schedule.  At the point all the info schedule info was shown on the node. Now it is on the term view. We may not need these fields or the field token module anymore.

## Task

- [x] Check to see if any of these fields are being used anywhere
  - `field_active_period`
  - `field_final_disposition`
  -  `field_semi_active_period`
  - `field_special_flags`
- [x] Delete any unused fields
- [x] Check to see if `field_token_value` module is used anywhere
- [x] remove `field_token_value` if it is not used anywhere
- [x] remove references to fields deleted in stem 2 from the docs (@CraigClark can do this)

**Comment by lkmorlan** [comment]
The fields and module have been removed. @CraigClark over to you.

**Comment by CraigClark** [comment]
Tested and approved on dv14 for fields, documentation references to these fields have been removed on prod

**Comment by lkmorlan** [comment]
To get this to deploy, I use three separate deployments to re-install `field_token_value`, uninstall it, and then remove it from Composer.
