### ISSUE TITLE
Style fixes | keep this open

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#410]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6381923925

---

This task will stay open. It's for small changes we need to make to the theme. These changes aren't big enough to need their own issue,  but they're still important to keep track of.

- [x] Increase spacing between items on the data dictionary paragraph edit form. see #409 
- [x] more space below logo on header so logo is horizontally centred    
  <img width="1444" alt="image" src="https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/6f079e98-c0bf-4fd2-9a49-9999b19fc88b">
- [x] Additional space above _active period_ on info schedule term page as per [#392](https://github.com/bcgov/MFIN-Data-Catalogue/issues/392#issuecomment-2033284760)
- [x] Add margin to top of footer for readability  
   <img width="739" alt="image" src="https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/4cdd45bf-06b3-4de6-bacd-f6c8aa49ee35">
- [x] Move devel styles to proper style sheets
- [x] Decrease spacing between page title and underline
- [x] fix inconsistent font weight on field labels on build pages form view
- [x] add space above sidebar on mobile  
   <img width="760" alt="image" src="https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/c5c0e845-9802-40a0-bd22-c3b595b83322">
- [x] ensure consistency across the reports - done as part of #441 
- [x] make the manage page use the same exposed filter style as the report builder
- [x] on dashboard, move search bar to the header and make the manage records look decent
- [x] make sure all booleans are explicit yes/no and display inline (pending @NicoledeGreef approval)
- [x] ~~Fix sidebar on book pages that touch the side of the screen on mobile~~
- [x] in the build pages, source system has too much space between the label and the input field

**Comment by CraigClark** [comment]
@lkmorlan Please review/merge:

- [x] Data catalogue spacing styles https://github.com/bcgov/MFIN-Data-Catalogue/tree/410-spacing-issues
- [x] base theme spacing adjustments https://github.com/bcgov/bcbb-theme/tree/410-dc-spacing-issues

**Comment by lkmorlan** [comment]
Merged

**Comment by CraigClark** [comment]
@lkmorlan please review/merge

- [x] Data catalogue changes https://github.com/bcgov/MFIN-Data-Catalogue/tree/410-move-devel-styles-to-theme
- [x] Base theme changes https://github.com/bcgov/bcbb-theme/tree/410-dc-move-devel-styles-to-theme

**Comment by lkmorlan** [comment]
Merged

**Comment by CraigClark** [comment]
inconsistent labels fixed with this [commit](https://github.com/bcgov/MFIN-Data-Catalogue/commit/0fb82aac1d6766b4e273ff67f1dc4559fb0835e4) on this [branch](https://github.com/bcgov/MFIN-Data-Catalogue/tree/410-theme-fixes)

**Comment by CraigClark** [comment]
Search box moved to header and display of manage records on dashboard fixed with [this commit](https://github.com/bcgov/MFIN-Data-Catalogue/commit/f378e81a1e0dadc13e15b9a7ba852e7dab13c93f)

**Comment by CraigClark** [comment]
@NicoledeGreef I'm thinking booleans would be better as radios. It is more explicit than a checkbox. It would require an editor to choose between yes and no.

instead of 


![Image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/0752b897-28ab-4524-bc43-b5f47a80f618)

We would have 

![Image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/4bf850b8-24d4-4078-a8ae-f471f4adc6a9)

This would make it work the same way as _Personal information_, the only other boolean currently in use.

Do you approve this change?

**Comment by CraigClark** [comment]
Manage records page has same design as report pages with [this commit](https://github.com/bcgov/MFIN-Data-Catalogue/commit/be68f72aed50b321faaeae52c1948419c12edfcd)

It wound be nice at some point to format the sort choices as radios. There is no option for this in UI, it would require custom code.

**Comment by lkmorlan** [comment]
Merged

**Comment by CraigClark** [comment]
Booleans  made explicit with this branch https://github.com/bcgov/MFIN-Data-Catalogue/tree/410-booleans-to-explicit-yes-no @lkmorlan to review/merge

**Comment by CraigClark** [comment]
Sidebar nav touching side of screen on mobile is no longer an issue. A while ago I remove a bootstrap gap glass that was wrapping the entire container, that may have fixed it.

**Comment by CraigClark** [comment]
Space added above sidebar on mobile fixed in this branch https://github.com/bcgov/MFIN-Data-Catalogue/tree/410-fix-spacing-on-side-bar
@lkmorlan please review/merge.

**Comment by lkmorlan** [comment]
Merged

**Comment by CraigClark** [comment]
- [x] Appearance of *series* field fixed by this branch https://github.com/bcgov/MFIN-Data-Catalogue/tree/410-series-field

@lkmorlan please review/merge

**Comment by lkmorlan** [comment]
Merged

**Comment by CraigClark** [comment]
Closing this. All documented adjustments are done and there is no time left in the project for additional changes.
