### ISSUE TITLE
New page template with better sidebars

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#460]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6560930060

---

The sidebar on the default page template goes 100% the height of the node. On all our displays where a two column layout is used, the sidebar stops at the height of the content.

## Task

On the dc theme, make a new page template.
- [x] make a new page template with a layout more suitable to the dc design
- [x] set blocks on block page to the correct regions
- [x] remove regions not used in the data-catalogue, such as first sidebar.

**Comment by CraigClark** [comment]
@lkmorlan for review/merge https://github.com/bcgov/MFIN-Data-Catalogue/tree/460-dc-specific-page-template

Once this is merged, I'll rebase and continue with book search style

**Comment by lkmorlan** [comment]
Merged
